### ISSUE TITLE
OC 8.0A8 Collar won't allow detach after unlocking

### ISSUE THREAD

**Issue by boundtight** [OpenCollarTeam/OpenCollar#422]
What version of OpenCollar are you using? OC 8.0 alpha 8, updated from alpha 6

What behavior did you expect? When collar is unlocked collar should be able to be detached. Also, contents should be editable

What behavior did you see instead? Collar cannot be removed due to RLV restrictions. Contents also cannot be edited (typical RLV behavior of a locked item). Using the debug-unweld command fixes the issue and allows the collar to be detached but the 'WELD' option was never used.

What steps does someone need to take to reproduce the problem? Update a collar to alpha 8 and lock it. Then unlock it and attempt to detach the collar

**Comment by zontreck** [comment]
Known issue

**Comment by zontreck** [comment]
Fixed in Alpha 9

**Comment by pcbeeswing** [comment]
I  had this issue tonight when updating to the latest release.

**Comment by boundtight** [comment]
Just updated an older 7.3 collar to 8.2.1 and this is still an issue
