### ISSUE TITLE
Eliminate arbitrary caps in oc_auth

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#70]
oc_auth currently limits you to at most 3 owners, 15 trusted, and 9 blocked.

Instead of those arbitrary caps, we could just set an overall limit of X number of saved people, split up in whatever way the user wants.  If we set it at 27 then we'd still have the same overall memory bound as the current script, but with a lot more flexibility.  Even better would be to do some testing on how high it can go before we start getting memory errors, and use that as the cap.

**Comment by silentwar-resident** [comment]
Agreed lets try that.

**Comment by pixelwork** [comment]
code for that already exists. i think it should be easy to merge it into our branch.
it kind of works like silentwar suggested, it sets a upper limit for owners + trusts + blocks and while adding ppl to this lists sums it up and checks against that limit, even showing a nice percentage use.

that code also makes selfowned a mode of its own, instead of just adding you to the owner list, in fact it does not add you to the owner list but directly tests if selfowned is active, so it saves a few list operations.

i already have merged that code for testing purposes and can create a pull request later if desired. currently still testing it for myself.

**Comment by pixelwork** [comment]
i merged the code into my fork
https://github.com/pixelwork/OpenCollarTeam/commit/3de848cb7ce1d2be142ee4d720b9247652c715bd

so far my tests are successful with that code, let me know if it is worth a pull request

**Comment by CorwinDavidson** [comment]
If you want to get a little creative there is a way to have a limit pf 54 of each not waste the script space by keeping this information in memory.

I was working on this for an unreleased version of the CollardDB fork.  You can use llGetLinkMedia and llSetLinkMedia to store the auth lists and only load them when needed.

I was using lslForge at the time as an experiment so some of the code is in a library vs in the auth code file:

https://github.com/CorwinDavidson/CollarDB-NextGen/blob/4f5fb04defacc10946cc93d2d49a8bac5061026b/Core/CDB%20-%20auth.lslp

Library Functions: 

https://github.com/CorwinDavidson/CollarDB-NextGen/blob/4f5fb04defacc10946cc93d2d49a8bac5061026b/lib/CommonFunctions.lslm#L154-L311

**Comment by nirea** [comment]
Very clever hack, Corwin!  It looks like it would save memory when the auth
lists aren't actively being checked or modified, but inside getAuthList and
setAuthList we'd still have the full list in memory, as well as a
serialized string copy of that list.  So are we going to hit the memory
limit just as quickly?

When you say "54 of each", do you mean 54 owners, 54 trusted, 54 blocked?
I'm having a little trouble seeing how you get to those numbers.

Whether we have a consolidated limit/warning, or use Corwin's media storage
approach, the most important thing to me is that we actually test the max
number of owners/trusted/blocked that we can safely support.  Given how
often LSL ends up copying lists and strings, small differences in
implementation could mean big differences in the number of people we can
store.

**Comment by CorwinDavidson** [comment]
The keys are stored as a string with a "|" delimiter and stored in PRIM_MEDIA_HOME_URL and PRIM_MEDIA_WHITELIST on one face of of a prim per list (could be on the same face of seperate prims as well)

PRIM_MEDIA_HOME_URL and PRIM_MEDIA_WHITELIST can both have 1024 characters for a total of 2048, or a maximum of 27 keys stored pipe delimited as a string.

I'm rusty on my Auth List storage info, so if it stores both key and name the list length would need to be reduced appropriately... or you expand the storage by adding another llGetPrimMedia mapping for storage.

The more sides you have per prim the more storage locations you have.

**Comment by CorwinDavidson** [comment]
I'll see what I can do to get POC of this done with the 7.0 script set

**Comment by nirea** [comment]
So LSL does no validation of the strings set to PRIM_MEDIA_HOME_URL and
PRIM_MEDIA_WHITELIST?  They don't actually need to be valid URLs?

Another thought: since keys all have a fixed length, a string storing just
keys wouldn't even need a delimiter.  Even if we need to store names it
could be <key1><name1>|<key2><name2>|etc...  We can save a few bytes that
way.

**Comment by nirea** [comment]
We could also drop the dashes from the keys.

**Comment by CorwinDavidson** [comment]
I was looking into this in the past I didn't get a chance to play with it too much:

http://wiki.secondlife.com/wiki/Key_Compression  (Specifically the Base 256 Script script on top with the compress / decompress keys functions)

Once I get the POC working I can add in the compress / decompress of comparison

**Comment by CorwinDavidson** [comment]
My current POC code allows 25 of each Owner, Trust and Block.

**Comment by pixelwork** [comment]
opened pull request https://github.com/OpenCollarTeam/OpenCollar/pull/72 for discussion about what route to go

**Comment by CorwinDavidson** [comment]
POC code is available to review.  lists are set at 35 per list at the moment.
https://github.com/CorwinDavidson/OpenCollar/commits/auth_prim_media

Currently known issues:
* other scripts that use the lists as passed via link messages can and will crash due to the sizes.

**Comment by SatomiAhn** [comment]
This prim media trick is quite nice.

This means we can now finally get rid of all CMD_ZERO messages: oc_com could now directly read the prim properties and do the auth thing (Auth() function would be moved from oc_auth to oc_com), while oc_auth would just be used for auth configuration.

2 other scripts (oc_sys and oc_capture) also use CMD_ZERO:
- in oc_sys, it is just for handling the command "menuto", but as no local data is accessed, this can be moved to oc_com too.
- oc_capture asks to auth an adhoc command triggered on every collar touch (it has its own touch_start event). But it would be equivalent (in terms of behavior) to just react on CMD_EVERYONE messages with "menu" as command string. Besides, it makes sense that the capture routine should be triggered by any attempt to pop up the menu by a non-authed party.
- also oc_auth uses Auth() everywhere, but all these calls are spurious: nothing prevents oc_auth from behaving like a regular oc script and keeping the auth token initially computed by oc_com when the user entered the collar (by chat or touch).

It could be argued that an auth service that can be queried through a LM might still be useful. If it is really needed (with current scripts, it is not), CMD_ZERO messages could be handled by oc_com.

**Comment by CorwinDavidson** [comment]
You also have available three Boolean storage locations per prim face as well:
PRIM_MEDIA_AUTO_ZOOM
PRIM_MEDIA_AUTO_SCALE
PRIM_MEDIA_AUTO_LOOP

Given a normal cube you have 18 boolean storage locations + twelve 1024 byte string storage locations.

Add in Hollow and cut and you add another 6 boolean locations and another four 1024 byte string locations.

And this is all data that is persistent, short of a function to intentionally erase the data when a script resets, the data will be there

**Comment by CorwinDavidson** [comment]
Made some more changes, prep work to be able to implement #74

**Comment by nirea** [comment]
I've switched from per-list caps to a single cap of 28 people across all lists with 74d40b1141d27556f01ffa38d90e6de3d32a3256.  I'd still love to have the prim media solution someday, but I'll get 7.1 out with the simpler fix for now.

**Comment by zontreck** [comment]
@nirea 7.4 will add a advanced 'append' mode for settings. And with v8 we'll add the prim media solution. Either way with the caps or without notecard lines are limited to 255 bytes.

**Comment by SilkieSabra** [comment]
This was incorporated into OpenCollar V 7.4
